// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemKnowledgeHub.Api.Persistence;

#nullable disable

namespace SystemKnowledgeHub.Api.Persistence.Migrations
{
    [DbContext(typeof(KnowledgeHubDbContext))]
    [Migration("20260822025403_AddOidcAuthenticationFoundation")]
    partial class AddOidcAuthenticationFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.BusinessFunctions.Domain.BusinessFunction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CallerSummary")
                        .HasColumnType("TEXT")
                        .HasColumnName("caller_summary");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_name");

                    b.Property<string>("CreatedByRole")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_role");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("FunctionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("function_type");

                    b.Property<string>("InputDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("input_description");

                    b.Property<string>("KnowledgeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status");

                    b.Property<DateTimeOffset>("KnowledgeStatusChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_at");

                    b.Property<string>("KnowledgeStatusChangedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_name");

                    b.Property<string>("KnowledgeStatusChangedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_role");

                    b.Property<string>("KnowledgeStatusReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_reason");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<string>("OutputDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("output_description");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT")
                        .HasColumnName("purpose");

                    b.Property<string>("RewriteStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unknown")
                        .HasColumnName("rewrite_status");

                    b.Property<long>("SystemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("system_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeStatus");

                    b.HasIndex("SystemId", "Name")
                        .IsUnique();

                    b.HasIndex("SystemId", "FunctionType", "RewriteStatus", "KnowledgeStatus", "UpdatedAt");

                    b.ToTable("business_functions", null, t =>
                        {
                            t.HasCheckConstraint("ck_business_functions_knowledge_status", "knowledge_status IN ('Unknown','Inferred','Confirmed')");

                            t.HasCheckConstraint("ck_business_functions_rewrite_status", "rewrite_status IN ('Keep','Change','Remove','Unknown')");

                            t.HasCheckConstraint("ck_business_functions_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.BusinessFunctions.Domain.BusinessProcessStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("BusinessFunctionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("business_function_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_order");

                    b.HasKey("Id");

                    b.HasIndex("BusinessFunctionId", "StepOrder")
                        .IsUnique();

                    b.ToTable("business_process_steps", null, t =>
                        {
                            t.HasCheckConstraint("ck_business_process_steps_order", "step_order > 0");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.BusinessRules.Domain.BusinessRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ConditionText")
                        .HasColumnType("TEXT")
                        .HasColumnName("condition_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_name");

                    b.Property<string>("CreatedByRole")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_role");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("InputDataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("input_data_json");

                    b.Property<string>("KnowledgeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status");

                    b.Property<DateTimeOffset>("KnowledgeStatusChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_at");

                    b.Property<string>("KnowledgeStatusChangedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_name");

                    b.Property<string>("KnowledgeStatusChangedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_role");

                    b.Property<string>("KnowledgeStatusReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_reason");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<string>("ResultText")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_text");

                    b.Property<long>("SystemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("system_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeStatus");

                    b.HasIndex("SystemId", "Name")
                        .IsUnique();

                    b.HasIndex("SystemId", "KnowledgeStatus", "UpdatedAt");

                    b.ToTable("business_rules", null, t =>
                        {
                            t.HasCheckConstraint("ck_business_rules_input_data", "input_data_json IS NULL OR (json_valid(input_data_json) AND json_type(input_data_json) = 'array')");

                            t.HasCheckConstraint("ck_business_rules_knowledge_status", "knowledge_status IN ('Unknown','Inferred','Confirmed')");

                            t.HasCheckConstraint("ck_business_rules_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.ColumnKnownValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("DatabaseColumnId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("database_column_id");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("meaning");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value_text");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseColumnId", "ValueText")
                        .IsUnique();

                    b.HasIndex("DatabaseColumnId", "SortOrder", "ValueText");

                    b.ToTable("column_known_values", (string)null);
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseColumn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BusinessDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_description");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("column_name")
                        .UseCollation("NOCASE");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data_type");

                    b.Property<string>("DatabaseComment")
                        .HasColumnType("TEXT")
                        .HasColumnName("database_comment");

                    b.Property<long>("DatabaseObjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("database_object_id");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("default_value");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_nullable");

                    b.Property<string>("KnowledgeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status");

                    b.Property<DateTimeOffset>("KnowledgeStatusChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_at");

                    b.Property<string>("KnowledgeStatusChangedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_name");

                    b.Property<string>("KnowledgeStatusChangedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_role");

                    b.Property<string>("KnowledgeStatusReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_reason");

                    b.Property<int>("OrdinalPosition")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal_position");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ColumnName");

                    b.HasIndex("KnowledgeStatus");

                    b.HasIndex("DatabaseObjectId", "ColumnName")
                        .IsUnique();

                    b.HasIndex("DatabaseObjectId", "OrdinalPosition")
                        .IsUnique();

                    b.ToTable("database_columns", null, t =>
                        {
                            t.HasCheckConstraint("ck_database_columns_knowledge_status", "knowledge_status IN ('Unknown','Inferred','Confirmed')");

                            t.HasCheckConstraint("ck_database_columns_nullable", "is_nullable IN (0, 1)");

                            t.HasCheckConstraint("ck_database_columns_ordinal", "ordinal_position > 0");

                            t.HasCheckConstraint("ck_database_columns_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AccessMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("access_mode");

                    b.Property<string>("BusinessDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_description");

                    b.Property<string>("BusinessKeyColumnsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_key_columns_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_name");

                    b.Property<string>("CreatedByRole")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_role");

                    b.Property<long>("DatabaseSourceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("database_source_id");

                    b.Property<long?>("EstimatedRows")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estimated_rows");

                    b.Property<string>("KnowledgeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status");

                    b.Property<DateTimeOffset>("KnowledgeStatusChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_at");

                    b.Property<string>("KnowledgeStatusChangedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_name");

                    b.Property<string>("KnowledgeStatusChangedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_role");

                    b.Property<string>("KnowledgeStatusReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_reason");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("object_name")
                        .UseCollation("NOCASE");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("object_type");

                    b.Property<string>("PrimaryKeyColumnsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("primary_key_columns_json");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("schema_name")
                        .UseCollation("NOCASE");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeStatus");

                    b.HasIndex("ObjectName");

                    b.HasIndex("DatabaseSourceId", "SchemaName", "ObjectName")
                        .IsUnique();

                    b.HasIndex("DatabaseSourceId", "SchemaName", "ObjectType", "KnowledgeStatus");

                    b.ToTable("database_objects", null, t =>
                        {
                            t.HasCheckConstraint("ck_database_objects_access_mode", "access_mode IN ('Read','Write','ReadWrite','Unknown')");

                            t.HasCheckConstraint("ck_database_objects_business_keys", "business_key_columns_json IS NULL OR (json_valid(business_key_columns_json) AND json_type(business_key_columns_json) = 'array')");

                            t.HasCheckConstraint("ck_database_objects_knowledge_status", "knowledge_status IN ('Unknown','Inferred','Confirmed')");

                            t.HasCheckConstraint("ck_database_objects_primary_keys", "primary_key_columns_json IS NULL OR (json_valid(primary_key_columns_json) AND json_type(primary_key_columns_json) = 'array')");

                            t.HasCheckConstraint("ck_database_objects_rows", "estimated_rows IS NULL OR estimated_rows >= 0");

                            t.HasCheckConstraint("ck_database_objects_type", "object_type IN ('Table','View')");

                            t.HasCheckConstraint("ck_database_objects_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_name");

                    b.Property<string>("CreatedByRole")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_role");

                    b.Property<string>("DatabaseName")
                        .HasColumnType("TEXT")
                        .HasColumnName("database_name");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("engine");

                    b.Property<string>("Environment")
                        .HasColumnType("TEXT")
                        .HasColumnName("environment");

                    b.Property<string>("InstanceName")
                        .HasColumnType("TEXT")
                        .HasColumnName("instance_name");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<string>("ServiceName")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_name");

                    b.Property<long>("SystemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("system_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Engine");

                    b.HasIndex("SystemId")
                        .IsUnique()
                        .HasFilter("is_primary = 1");

                    b.HasIndex("SystemId", "Name")
                        .IsUnique();

                    b.HasIndex("SystemId", "IsPrimary", "Name");

                    b.ToTable("database_sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_database_sources_is_primary", "is_primary IN (0, 1)");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Evidence.Domain.Evidence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence_type");

                    b.Property<DateTimeOffset>("ProvidedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("provided_at");

                    b.Property<string>("ProviderEmployeeNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_employee_no");

                    b.Property<string>("ProviderExternalKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_external_key");

                    b.Property<string>("ProviderJobTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_job_title");

                    b.Property<long?>("ProviderKnowledgeRoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider_knowledge_role_id");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_name");

                    b.Property<string>("ProviderNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_note");

                    b.Property<string>("ProviderRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_role");

                    b.Property<string>("ProviderSource")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_source");

                    b.Property<string>("ProviderTeam")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_team");

                    b.Property<long?>("ProviderUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider_user_id");

                    b.Property<string>("SourceLocatorJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_locator_json");

                    b.Property<string>("SourceReference")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_reference")
                        .UseCollation("NOCASE");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_title");

                    b.Property<string>("SubjectDetailKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_detail_key");

                    b.Property<long>("SubjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_type");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("SupportReason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("support_reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProviderKnowledgeRoleId");

                    b.HasIndex("ProviderUserId");

                    b.HasIndex("SourceReference");

                    b.HasIndex("EvidenceType", "ProvidedAt")
                        .IsDescending(false, true);

                    b.HasIndex("SubjectType", "SubjectId", "SubjectDetailKey");

                    b.ToTable("evidence", null, t =>
                        {
                            t.HasCheckConstraint("ck_evidence_confidence", "confidence IS NULL OR confidence IN ('High','Medium','Low')");

                            t.HasCheckConstraint("ck_evidence_source_locator", "source_reference IS NOT NULL OR source_locator_json IS NOT NULL");

                            t.HasCheckConstraint("ck_evidence_source_locator_json", "source_locator_json IS NULL OR (json_valid(source_locator_json) AND json_type(source_locator_json) = 'object')");

                            t.HasCheckConstraint("ck_evidence_subject_type", "subject_type IN ('System','DatabaseSource','BusinessFunction','DatabaseObject','DatabaseColumn','BusinessRule','Integration','KnowledgeRelation','UnknownItem','Finding','Resolution','KnowledgeUpdate')");

                            t.HasCheckConstraint("ck_evidence_type", "evidence_type IN ('CodeReference','Sql','DatabaseSample','DatabaseComment','Api','MqMessage','ExistingDocument','HumanConfirmation')");

                            t.HasCheckConstraint("ck_evidence_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Integrations.Domain.Integration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_name");

                    b.Property<string>("CreatedByRole")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_role");

                    b.Property<long?>("DatabaseObjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("database_object_id");

                    b.Property<long?>("DatabaseSourceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("database_source_id");

                    b.Property<string>("EndpointDisplay")
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint_display")
                        .UseCollation("NOCASE");

                    b.Property<string>("EndpointJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint_json");

                    b.Property<string>("FlowDirection")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("flow_direction");

                    b.Property<string>("IntegrationType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("integration_type");

                    b.Property<string>("KnowledgeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status");

                    b.Property<DateTimeOffset>("KnowledgeStatusChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_at");

                    b.Property<string>("KnowledgeStatusChangedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_name");

                    b.Property<string>("KnowledgeStatusChangedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_role");

                    b.Property<string>("KnowledgeStatusReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_reason");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT")
                        .HasColumnName("purpose");

                    b.Property<string>("SourcePartyName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_party_name")
                        .UseCollation("NOCASE");

                    b.Property<long?>("SourceSystemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_system_id");

                    b.Property<string>("TargetPartyName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_party_name")
                        .UseCollation("NOCASE");

                    b.Property<long?>("TargetSystemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_system_id");

                    b.Property<string>("TopicOrQueue")
                        .HasColumnType("TEXT")
                        .HasColumnName("topic_or_queue");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseObjectId");

                    b.HasIndex("DatabaseSourceId");

                    b.HasIndex("EndpointDisplay");

                    b.HasIndex("IntegrationType", "KnowledgeStatus");

                    b.HasIndex("SourceSystemId", "IntegrationType");

                    b.HasIndex("TargetSystemId", "IntegrationType");

                    b.HasIndex("IntegrationType", "Name", "SourcePartyName", "TargetPartyName")
                        .IsUnique();

                    b.ToTable("integrations", null, t =>
                        {
                            t.HasCheckConstraint("ck_integrations_direction", "flow_direction IN ('OneWay','Bidirectional')");

                            t.HasCheckConstraint("ck_integrations_endpoint_json", "endpoint_json IS NULL OR json_valid(endpoint_json)");

                            t.HasCheckConstraint("ck_integrations_party_system", "source_system_id IS NOT NULL OR target_system_id IS NOT NULL");

                            t.HasCheckConstraint("ck_integrations_status", "knowledge_status IN ('Unknown','Inferred','Confirmed')");

                            t.HasCheckConstraint("ck_integrations_type", "integration_type IN ('HttpApi','RabbitMq','FileExchange','DatabaseDependency')");

                            t.HasCheckConstraint("ck_integrations_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Integrations.Domain.IntegrationContractField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DataType")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_type");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("field_name")
                        .UseCollation("NOCASE");

                    b.Property<long>("IntegrationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("integration_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_required");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("SampleValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("sample_value");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId", "FieldName")
                        .IsUnique();

                    b.HasIndex("IntegrationId", "Ordinal")
                        .IsUnique();

                    b.ToTable("integration_contract_fields", null, t =>
                        {
                            t.HasCheckConstraint("ck_integration_contract_fields_ordinal", "ordinal > 0");

                            t.HasCheckConstraint("ck_integration_contract_fields_required", "is_required IN (0,1)");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Relationships.Domain.KnowledgeRelation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_name");

                    b.Property<string>("CreatedByRole")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_role");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("KnowledgeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status");

                    b.Property<DateTimeOffset>("KnowledgeStatusChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_at");

                    b.Property<string>("KnowledgeStatusChangedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_name");

                    b.Property<string>("KnowledgeStatusChangedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_role");

                    b.Property<string>("KnowledgeStatusReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_reason");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("relation_type");

                    b.Property<long>("SourceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<long>("TargetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("RelationType", "KnowledgeStatus");

                    b.HasIndex("SourceType", "SourceId", "RelationType");

                    b.HasIndex("TargetType", "TargetId", "RelationType");

                    b.HasIndex("SourceType", "SourceId", "TargetType", "TargetId", "RelationType")
                        .IsUnique();

                    b.ToTable("knowledge_relations", null, t =>
                        {
                            t.HasCheckConstraint("ck_knowledge_relations_distinct_endpoints", "source_type <> target_type OR source_id <> target_id");

                            t.HasCheckConstraint("ck_knowledge_relations_relation_type", "relation_type IN ('Calls','Reads','Writes','UsesField','AppliesRule','PublishesVia','ConsumesVia','UsesIntegration','DependsOn')");

                            t.HasCheckConstraint("ck_knowledge_relations_source_type", "source_type IN ('System','DatabaseSource','BusinessFunction','DatabaseObject','DatabaseColumn','BusinessRule','Integration')");

                            t.HasCheckConstraint("ck_knowledge_relations_status", "knowledge_status IN ('Unknown','Inferred','Confirmed')");

                            t.HasCheckConstraint("ck_knowledge_relations_target_type", "target_type IN ('System','DatabaseSource','BusinessFunction','DatabaseObject','DatabaseColumn','BusinessRule','Integration')");

                            t.HasCheckConstraint("ck_knowledge_relations_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Systems.Domain.KnowledgeSystem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_name");

                    b.Property<string>("CreatedByRole")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_role");

                    b.Property<string>("DeploymentJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("deployment_json");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("KnowledgeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status");

                    b.Property<DateTimeOffset>("KnowledgeStatusChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_at");

                    b.Property<string>("KnowledgeStatusChangedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_name");

                    b.Property<string>("KnowledgeStatusChangedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_role");

                    b.Property<string>("KnowledgeStatusReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_reason");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lifecycle");

                    b.Property<string>("MainEntryPointsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("main_entry_points_json");

                    b.Property<string>("MainProjectsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("main_projects_json");

                    b.Property<string>("MainUsersJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("main_users_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT")
                        .HasColumnName("purpose");

                    b.Property<string>("RepositoryName")
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_name");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_url");

                    b.Property<string>("SystemType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("system_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeStatus");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Lifecycle", "KnowledgeStatus", "UpdatedAt");

                    b.ToTable("systems", null, t =>
                        {
                            t.HasCheckConstraint("ck_systems_deployment_json", "deployment_json IS NULL OR (json_valid(deployment_json) AND json_type(deployment_json) = 'array')");

                            t.HasCheckConstraint("ck_systems_entry_points_json", "main_entry_points_json IS NULL OR (json_valid(main_entry_points_json) AND json_type(main_entry_points_json) = 'array')");

                            t.HasCheckConstraint("ck_systems_knowledge_status", "knowledge_status IN ('Unknown','Inferred','Confirmed')");

                            t.HasCheckConstraint("ck_systems_lifecycle", "lifecycle IN ('Planned','InDevelopment','Running','Maintaining','Legacy','Retired')");

                            t.HasCheckConstraint("ck_systems_main_projects_json", "main_projects_json IS NULL OR (json_valid(main_projects_json) AND json_type(main_projects_json) = 'array')");

                            t.HasCheckConstraint("ck_systems_main_users_json", "main_users_json IS NULL OR (json_valid(main_users_json) AND json_type(main_users_json) = 'array')");

                            t.HasCheckConstraint("ck_systems_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Systems.Domain.SystemTechnologyTag", b =>
                {
                    b.Property<long>("SystemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("system_id");

                    b.Property<string>("Technology")
                        .HasColumnType("TEXT")
                        .HasColumnName("technology")
                        .UseCollation("NOCASE");

                    b.HasKey("SystemId", "Technology");

                    b.HasIndex("Technology", "SystemId");

                    b.ToTable("system_technology_tags", (string)null);
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.Finding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RecordedByExternalKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_by_external_key");

                    b.Property<string>("RecordedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_by_name");

                    b.Property<string>("RecordedByNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_by_note");

                    b.Property<string>("RecordedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_by_role");

                    b.Property<string>("RecordedBySource")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_by_source");

                    b.Property<string>("RecordedByTeam")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_by_team");

                    b.Property<long>("UnknownItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unknown_item_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("UnknownItemId", "RecordedAt");

                    b.ToTable("findings", (string)null);
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.KnowledgeUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("after_json");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_at");

                    b.Property<string>("AppliedByExternalKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_by_external_key");

                    b.Property<string>("AppliedByName")
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_by_name");

                    b.Property<string>("AppliedByNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_by_note");

                    b.Property<string>("AppliedByRole")
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_by_role");

                    b.Property<string>("AppliedBySource")
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_by_source");

                    b.Property<string>("AppliedByTeam")
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_by_team");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("before_json");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("change_summary");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("KnowledgeStatusAfter")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_after");

                    b.Property<string>("KnowledgeStatusBefore")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_before");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("SubjectDetailKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_detail_key");

                    b.Property<long>("TargetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_type");

                    b.Property<long>("UnknownItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unknown_item_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status", "AppliedAt");

                    b.HasIndex("TargetType", "TargetId");

                    b.HasIndex("UnknownItemId", "Status");

                    b.ToTable("knowledge_updates", null, t =>
                        {
                            t.HasCheckConstraint("ck_knowledge_updates_after_json", "json_valid(after_json)");

                            t.HasCheckConstraint("ck_knowledge_updates_applied_snapshot", "status = 'Proposed' OR (applied_by_name IS NOT NULL AND applied_by_role IS NOT NULL AND applied_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_knowledge_updates_before_json", "json_valid(before_json)");

                            t.HasCheckConstraint("ck_knowledge_updates_status", "status IN ('Proposed','Applied')");

                            t.HasCheckConstraint("ck_knowledge_updates_status_pair", "(knowledge_status_before IS NULL AND knowledge_status_after IS NULL) OR (knowledge_status_before IS NOT NULL AND knowledge_status_after IS NOT NULL)");

                            t.HasCheckConstraint("ck_knowledge_updates_target_type", "target_type IN ('System','DatabaseSource','BusinessFunction','DatabaseObject','DatabaseColumn','BusinessRule','Integration')");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.Resolution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("conclusion");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ConfirmedByExternalKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_by_external_key");

                    b.Property<string>("ConfirmedByName")
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_by_name");

                    b.Property<string>("ConfirmedByNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_by_note");

                    b.Property<string>("ConfirmedByRole")
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_by_role");

                    b.Property<string>("ConfirmedBySource")
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_by_source");

                    b.Property<string>("ConfirmedByTeam")
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_by_team");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("UnknownItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unknown_item_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("UnknownItemId")
                        .IsUnique();

                    b.ToTable("resolutions", (string)null);
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.UnknownItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset?>("ConclusionConfirmedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("conclusion_confirmed_at");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT")
                        .HasColumnName("context");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_name");

                    b.Property<string>("CreatedByRole")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_role");

                    b.Property<DateTimeOffset?>("InvestigationStartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("investigation_started_at");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_code")
                        .UseCollation("NOCASE");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("priority");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("question");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("SystemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("system_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.HasIndex("Priority", "Status");

                    b.HasIndex("Status", "UpdatedAt");

                    b.HasIndex("SystemId", "Status", "Priority", "UpdatedAt");

                    b.ToTable("unknown_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_unknown_items_priority", "priority IN ('High','Medium','Low')");

                            t.HasCheckConstraint("ck_unknown_items_status", "status IN ('Open','Investigating','ConclusionConfirmed','Closed')");

                            t.HasCheckConstraint("ck_unknown_items_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.UnknownItemActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("activity_type");

                    b.Property<string>("ActorExternalKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_external_key");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_name");

                    b.Property<string>("ActorNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_note");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_role");

                    b.Property<string>("ActorSource")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_source");

                    b.Property<string>("ActorTeam")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_team");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<long?>("RelatedId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("related_id");

                    b.Property<string>("RelatedType")
                        .HasColumnType("TEXT")
                        .HasColumnName("related_type");

                    b.Property<long>("UnknownItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unknown_item_id");

                    b.HasKey("Id");

                    b.HasIndex("RelatedType", "RelatedId");

                    b.HasIndex("UnknownItemId", "OccurredAt", "Id");

                    b.ToTable("unknown_item_activities", null, t =>
                        {
                            t.HasCheckConstraint("ck_unknown_item_activities_related_pair", "(related_type IS NULL AND related_id IS NULL) OR (related_type IS NOT NULL AND related_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_unknown_item_activities_related_type", "related_type IS NULL OR related_type IN ('Finding','Evidence','Resolution','KnowledgeUpdate')");

                            t.HasCheckConstraint("ck_unknown_item_activities_type", "activity_type IN ('Created','StatusChanged','FindingAdded','EvidenceAdded','ResolutionRecorded','KnowledgeUpdateApplied','Closed','Reopened')");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.UnknownItemTarget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DisplaySnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_snapshot");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary");

                    b.Property<long>("TargetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_type");

                    b.Property<long>("UnknownItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unknown_item_id");

                    b.HasKey("Id");

                    b.HasIndex("UnknownItemId")
                        .IsUnique()
                        .HasFilter("is_primary = 1");

                    b.HasIndex("UnknownItemId", "IsPrimary");

                    b.HasIndex("TargetType", "TargetId", "UnknownItemId");

                    b.HasIndex("UnknownItemId", "TargetType", "TargetId")
                        .IsUnique();

                    b.ToTable("unknown_item_targets", null, t =>
                        {
                            t.HasCheckConstraint("ck_unknown_item_targets_primary", "is_primary IN (0,1)");

                            t.HasCheckConstraint("ck_unknown_item_targets_type", "target_type IN ('System','DatabaseSource','BusinessFunction','DatabaseObject','DatabaseColumn','BusinessRule','Integration')");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Users.Domain.KnowledgeRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("IsActive", "Name");

                    b.ToTable("knowledge_roles", null, t =>
                        {
                            t.HasCheckConstraint("ck_knowledge_roles_is_active", "is_active IN (0,1)");

                            t.HasCheckConstraint("ck_knowledge_roles_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Users.Domain.LoginIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique();

                    b.ToTable("login_identities", null, t =>
                        {
                            t.HasCheckConstraint("ck_login_identities_is_active", "is_active IN (0,1)");

                            t.HasCheckConstraint("ck_login_identities_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Users.Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Viewer")
                        .HasColumnName("access_level");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartmentOrTeam")
                        .HasColumnType("TEXT")
                        .HasColumnName("department_or_team");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name")
                        .UseCollation("NOCASE");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email")
                        .UseCollation("NOCASE");

                    b.Property<string>("EmployeeNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_no")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("EmployeeNo")
                        .IsUnique()
                        .HasFilter("employee_no IS NOT NULL");

                    b.HasIndex("IsActive", "DisplayName");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_access_level", "access_level IN ('Viewer','Editor','Administrator')");

                            t.HasCheckConstraint("ck_users_is_active", "is_active IN (0,1)");

                            t.HasCheckConstraint("ck_users_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Users.Domain.UserKnowledgeRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<long>("KnowledgeRoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("knowledge_role_id");

                    b.HasKey("UserId", "KnowledgeRoleId");

                    b.HasIndex("KnowledgeRoleId");

                    b.ToTable("user_knowledge_roles", (string)null);
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.BusinessFunctions.Domain.BusinessFunction", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.Systems.Domain.KnowledgeSystem", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.BusinessFunctions.Domain.BusinessProcessStep", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.BusinessFunctions.Domain.BusinessFunction", "BusinessFunction")
                        .WithMany("ProcessSteps")
                        .HasForeignKey("BusinessFunctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessFunction");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.BusinessRules.Domain.BusinessRule", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.Systems.Domain.KnowledgeSystem", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.ColumnKnownValue", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseColumn", "DatabaseColumn")
                        .WithMany("KnownValues")
                        .HasForeignKey("DatabaseColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatabaseColumn");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseColumn", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseObject", "DatabaseObject")
                        .WithMany("Columns")
                        .HasForeignKey("DatabaseObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatabaseObject");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseObject", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseSource", "DatabaseSource")
                        .WithMany("DatabaseObjects")
                        .HasForeignKey("DatabaseSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatabaseSource");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseSource", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.Systems.Domain.KnowledgeSystem", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Evidence.Domain.Evidence", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.Users.Domain.KnowledgeRole", null)
                        .WithMany()
                        .HasForeignKey("ProviderKnowledgeRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SystemKnowledgeHub.Api.Features.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ProviderUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Integrations.Domain.Integration", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseObject", "DatabaseObject")
                        .WithMany()
                        .HasForeignKey("DatabaseObjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseSource", "DatabaseSource")
                        .WithMany()
                        .HasForeignKey("DatabaseSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SystemKnowledgeHub.Api.Features.Systems.Domain.KnowledgeSystem", "SourceSystem")
                        .WithMany()
                        .HasForeignKey("SourceSystemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SystemKnowledgeHub.Api.Features.Systems.Domain.KnowledgeSystem", "TargetSystem")
                        .WithMany()
                        .HasForeignKey("TargetSystemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DatabaseObject");

                    b.Navigation("DatabaseSource");

                    b.Navigation("SourceSystem");

                    b.Navigation("TargetSystem");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Integrations.Domain.IntegrationContractField", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.Integrations.Domain.Integration", "Integration")
                        .WithMany("ContractFields")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Systems.Domain.SystemTechnologyTag", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.Systems.Domain.KnowledgeSystem", "System")
                        .WithMany("TechnologyTags")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.Finding", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.UnknownItem", "UnknownItem")
                        .WithMany("Findings")
                        .HasForeignKey("UnknownItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnknownItem");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.KnowledgeUpdate", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.UnknownItem", "UnknownItem")
                        .WithMany("KnowledgeUpdates")
                        .HasForeignKey("UnknownItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnknownItem");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.Resolution", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.UnknownItem", "UnknownItem")
                        .WithOne("Resolution")
                        .HasForeignKey("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.Resolution", "UnknownItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnknownItem");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.UnknownItem", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.Systems.Domain.KnowledgeSystem", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.UnknownItemActivity", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.UnknownItem", "UnknownItem")
                        .WithMany("Activities")
                        .HasForeignKey("UnknownItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnknownItem");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.UnknownItemTarget", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.UnknownItem", "UnknownItem")
                        .WithMany("Targets")
                        .HasForeignKey("UnknownItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnknownItem");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Users.Domain.LoginIdentity", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Users.Domain.UserKnowledgeRole", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.Users.Domain.KnowledgeRole", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemKnowledgeHub.Api.Features.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.BusinessFunctions.Domain.BusinessFunction", b =>
                {
                    b.Navigation("ProcessSteps");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseColumn", b =>
                {
                    b.Navigation("KnownValues");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseObject", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseSource", b =>
                {
                    b.Navigation("DatabaseObjects");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Integrations.Domain.Integration", b =>
                {
                    b.Navigation("ContractFields");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Systems.Domain.KnowledgeSystem", b =>
                {
                    b.Navigation("TechnologyTags");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.UnknownItems.Domain.UnknownItem", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Findings");

                    b.Navigation("KnowledgeUpdates");

                    b.Navigation("Resolution");

                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
