// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemKnowledgeHub.Api.Persistence;

#nullable disable

namespace SystemKnowledgeHub.Api.Persistence.Migrations
{
    [DbContext(typeof(KnowledgeHubDbContext))]
    [Migration("20260814103948_AddBusinessFunctions")]
    partial class AddBusinessFunctions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.BusinessFunctions.Domain.BusinessFunction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CallerSummary")
                        .HasColumnType("TEXT")
                        .HasColumnName("caller_summary");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_name");

                    b.Property<string>("CreatedByRole")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_role");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("FunctionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("function_type");

                    b.Property<string>("InputDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("input_description");

                    b.Property<string>("KnowledgeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status");

                    b.Property<DateTimeOffset>("KnowledgeStatusChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_at");

                    b.Property<string>("KnowledgeStatusChangedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_name");

                    b.Property<string>("KnowledgeStatusChangedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_role");

                    b.Property<string>("KnowledgeStatusReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_reason");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<string>("OutputDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("output_description");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT")
                        .HasColumnName("purpose");

                    b.Property<string>("RewriteStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unknown")
                        .HasColumnName("rewrite_status");

                    b.Property<long>("SystemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("system_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeStatus");

                    b.HasIndex("SystemId", "Name")
                        .IsUnique();

                    b.HasIndex("SystemId", "FunctionType", "RewriteStatus", "KnowledgeStatus", "UpdatedAt");

                    b.ToTable("business_functions", null, t =>
                        {
                            t.HasCheckConstraint("ck_business_functions_knowledge_status", "knowledge_status IN ('Unknown','Inferred','Confirmed')");

                            t.HasCheckConstraint("ck_business_functions_rewrite_status", "rewrite_status IN ('Keep','Change','Remove','Unknown')");

                            t.HasCheckConstraint("ck_business_functions_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.BusinessFunctions.Domain.BusinessProcessStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("BusinessFunctionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("business_function_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_order");

                    b.HasKey("Id");

                    b.HasIndex("BusinessFunctionId", "StepOrder")
                        .IsUnique();

                    b.ToTable("business_process_steps", null, t =>
                        {
                            t.HasCheckConstraint("ck_business_process_steps_order", "step_order > 0");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.ColumnKnownValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("DatabaseColumnId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("database_column_id");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("meaning");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value_text");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseColumnId", "ValueText")
                        .IsUnique();

                    b.HasIndex("DatabaseColumnId", "SortOrder", "ValueText");

                    b.ToTable("column_known_values", (string)null);
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseColumn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BusinessDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_description");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("column_name")
                        .UseCollation("NOCASE");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data_type");

                    b.Property<string>("DatabaseComment")
                        .HasColumnType("TEXT")
                        .HasColumnName("database_comment");

                    b.Property<long>("DatabaseObjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("database_object_id");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("default_value");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_nullable");

                    b.Property<string>("KnowledgeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status");

                    b.Property<DateTimeOffset>("KnowledgeStatusChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_at");

                    b.Property<string>("KnowledgeStatusChangedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_name");

                    b.Property<string>("KnowledgeStatusChangedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_role");

                    b.Property<string>("KnowledgeStatusReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_reason");

                    b.Property<int>("OrdinalPosition")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal_position");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ColumnName");

                    b.HasIndex("KnowledgeStatus");

                    b.HasIndex("DatabaseObjectId", "ColumnName")
                        .IsUnique();

                    b.HasIndex("DatabaseObjectId", "OrdinalPosition")
                        .IsUnique();

                    b.ToTable("database_columns", null, t =>
                        {
                            t.HasCheckConstraint("ck_database_columns_knowledge_status", "knowledge_status IN ('Unknown','Inferred','Confirmed')");

                            t.HasCheckConstraint("ck_database_columns_nullable", "is_nullable IN (0, 1)");

                            t.HasCheckConstraint("ck_database_columns_ordinal", "ordinal_position > 0");

                            t.HasCheckConstraint("ck_database_columns_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AccessMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("access_mode");

                    b.Property<string>("BusinessDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_description");

                    b.Property<string>("BusinessKeyColumnsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_key_columns_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_name");

                    b.Property<string>("CreatedByRole")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_role");

                    b.Property<long>("DatabaseSourceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("database_source_id");

                    b.Property<long?>("EstimatedRows")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estimated_rows");

                    b.Property<string>("KnowledgeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status");

                    b.Property<DateTimeOffset>("KnowledgeStatusChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_at");

                    b.Property<string>("KnowledgeStatusChangedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_name");

                    b.Property<string>("KnowledgeStatusChangedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_role");

                    b.Property<string>("KnowledgeStatusReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_reason");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("object_name")
                        .UseCollation("NOCASE");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("object_type");

                    b.Property<string>("PrimaryKeyColumnsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("primary_key_columns_json");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("schema_name")
                        .UseCollation("NOCASE");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeStatus");

                    b.HasIndex("ObjectName");

                    b.HasIndex("DatabaseSourceId", "SchemaName", "ObjectName")
                        .IsUnique();

                    b.HasIndex("DatabaseSourceId", "SchemaName", "ObjectType", "KnowledgeStatus");

                    b.ToTable("database_objects", null, t =>
                        {
                            t.HasCheckConstraint("ck_database_objects_access_mode", "access_mode IN ('Read','Write','ReadWrite','Unknown')");

                            t.HasCheckConstraint("ck_database_objects_business_keys", "business_key_columns_json IS NULL OR (json_valid(business_key_columns_json) AND json_type(business_key_columns_json) = 'array')");

                            t.HasCheckConstraint("ck_database_objects_knowledge_status", "knowledge_status IN ('Unknown','Inferred','Confirmed')");

                            t.HasCheckConstraint("ck_database_objects_primary_keys", "primary_key_columns_json IS NULL OR (json_valid(primary_key_columns_json) AND json_type(primary_key_columns_json) = 'array')");

                            t.HasCheckConstraint("ck_database_objects_rows", "estimated_rows IS NULL OR estimated_rows >= 0");

                            t.HasCheckConstraint("ck_database_objects_type", "object_type IN ('Table','View')");

                            t.HasCheckConstraint("ck_database_objects_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_name");

                    b.Property<string>("CreatedByRole")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_role");

                    b.Property<string>("DatabaseName")
                        .HasColumnType("TEXT")
                        .HasColumnName("database_name");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("engine");

                    b.Property<string>("Environment")
                        .HasColumnType("TEXT")
                        .HasColumnName("environment");

                    b.Property<string>("InstanceName")
                        .HasColumnType("TEXT")
                        .HasColumnName("instance_name");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<string>("ServiceName")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_name");

                    b.Property<long>("SystemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("system_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Engine");

                    b.HasIndex("SystemId")
                        .IsUnique()
                        .HasFilter("is_primary = 1");

                    b.HasIndex("SystemId", "Name")
                        .IsUnique();

                    b.HasIndex("SystemId", "IsPrimary", "Name");

                    b.ToTable("database_sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_database_sources_is_primary", "is_primary IN (0, 1)");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Systems.Domain.KnowledgeSystem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_name");

                    b.Property<string>("CreatedByRole")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_role");

                    b.Property<string>("DeploymentJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("deployment_json");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("KnowledgeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status");

                    b.Property<DateTimeOffset>("KnowledgeStatusChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_at");

                    b.Property<string>("KnowledgeStatusChangedByName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_name");

                    b.Property<string>("KnowledgeStatusChangedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_changed_by_role");

                    b.Property<string>("KnowledgeStatusReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_status_reason");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lifecycle");

                    b.Property<string>("MainEntryPointsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("main_entry_points_json");

                    b.Property<string>("MainProjectsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("main_projects_json");

                    b.Property<string>("MainUsersJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("main_users_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT")
                        .HasColumnName("purpose");

                    b.Property<string>("RepositoryName")
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_name");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_url");

                    b.Property<string>("SystemType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("system_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeStatus");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Lifecycle", "KnowledgeStatus", "UpdatedAt");

                    b.ToTable("systems", null, t =>
                        {
                            t.HasCheckConstraint("ck_systems_deployment_json", "deployment_json IS NULL OR (json_valid(deployment_json) AND json_type(deployment_json) = 'array')");

                            t.HasCheckConstraint("ck_systems_entry_points_json", "main_entry_points_json IS NULL OR (json_valid(main_entry_points_json) AND json_type(main_entry_points_json) = 'array')");

                            t.HasCheckConstraint("ck_systems_knowledge_status", "knowledge_status IN ('Unknown','Inferred','Confirmed')");

                            t.HasCheckConstraint("ck_systems_lifecycle", "lifecycle IN ('Planned','InDevelopment','Running','Maintaining','Legacy','Retired')");

                            t.HasCheckConstraint("ck_systems_main_projects_json", "main_projects_json IS NULL OR (json_valid(main_projects_json) AND json_type(main_projects_json) = 'array')");

                            t.HasCheckConstraint("ck_systems_main_users_json", "main_users_json IS NULL OR (json_valid(main_users_json) AND json_type(main_users_json) = 'array')");

                            t.HasCheckConstraint("ck_systems_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Systems.Domain.SystemTechnologyTag", b =>
                {
                    b.Property<long>("SystemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("system_id");

                    b.Property<string>("Technology")
                        .HasColumnType("TEXT")
                        .HasColumnName("technology")
                        .UseCollation("NOCASE");

                    b.HasKey("SystemId", "Technology");

                    b.HasIndex("Technology", "SystemId");

                    b.ToTable("system_technology_tags", (string)null);
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.BusinessFunctions.Domain.BusinessFunction", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.Systems.Domain.KnowledgeSystem", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.BusinessFunctions.Domain.BusinessProcessStep", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.BusinessFunctions.Domain.BusinessFunction", "BusinessFunction")
                        .WithMany("ProcessSteps")
                        .HasForeignKey("BusinessFunctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessFunction");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.ColumnKnownValue", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseColumn", "DatabaseColumn")
                        .WithMany("KnownValues")
                        .HasForeignKey("DatabaseColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatabaseColumn");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseColumn", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseObject", "DatabaseObject")
                        .WithMany("Columns")
                        .HasForeignKey("DatabaseObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatabaseObject");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseObject", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseSource", "DatabaseSource")
                        .WithMany("DatabaseObjects")
                        .HasForeignKey("DatabaseSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatabaseSource");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseSource", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.Systems.Domain.KnowledgeSystem", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Systems.Domain.SystemTechnologyTag", b =>
                {
                    b.HasOne("SystemKnowledgeHub.Api.Features.Systems.Domain.KnowledgeSystem", "System")
                        .WithMany("TechnologyTags")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.BusinessFunctions.Domain.BusinessFunction", b =>
                {
                    b.Navigation("ProcessSteps");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseColumn", b =>
                {
                    b.Navigation("KnownValues");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseObject", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.DatabaseKnowledge.Domain.DatabaseSource", b =>
                {
                    b.Navigation("DatabaseObjects");
                });

            modelBuilder.Entity("SystemKnowledgeHub.Api.Features.Systems.Domain.KnowledgeSystem", b =>
                {
                    b.Navigation("TechnologyTags");
                });
#pragma warning restore 612, 618
        }
    }
}
