import type { ActorContext } from '../../../app/stores/actor'
import type { KnowledgeStatus } from '../../../api/contracts/knowledge'

export const integrationTypes = ['HttpApi', 'RabbitMq', 'FileExchange', 'DatabaseDependency'] as const
export type IntegrationType = (typeof integrationTypes)[number]
export const integrationTypeLabels: Readonly<Record<IntegrationType, string>> = { HttpApi: 'HTTP API', RabbitMq: 'RabbitMQ', FileExchange: '文件交换', DatabaseDependency: '数据库依赖' }
export const flowDirections = ['OneWay', 'Bidirectional'] as const
export type FlowDirection = (typeof flowDirections)[number]
export const flowDirectionLabels: Readonly<Record<FlowDirection, string>> = { OneWay: '单向', Bidirectional: '双向' }
export interface IntegrationParty { readonly systemId: number | null; readonly displayName: string }
export interface IntegrationEndpoint { readonly url: string | null; readonly method: string | null; readonly exchange: string | null; readonly topic: string | null; readonly queue: string | null; readonly filePath: string | null }
export interface IntegrationOverviewInput { readonly name: string; readonly integrationType: IntegrationType; readonly sourceParty: IntegrationParty; readonly targetParty: IntegrationParty; readonly flowDirection: FlowDirection; readonly purpose: string | null; readonly endpoint: Record<string, string | null>; readonly databaseSourceId: number | null; readonly databaseObjectId: number | null }
export interface IntegrationWriteInput extends IntegrationOverviewInput { readonly actor: ActorContext }
export interface IntegrationContractField { readonly order: number; readonly fieldName: string; readonly dataType: string | null; readonly required: boolean; readonly description: string | null; readonly sampleValue: string | null }
export interface IntegrationDetailResponse {
  readonly id: number; readonly concurrencyToken: string
  readonly header: { readonly name: string; readonly integrationType: IntegrationType; readonly knowledgeStatus: KnowledgeStatus }
  readonly sourceParty: IntegrationParty; readonly targetParty: IntegrationParty; readonly flowDirection: FlowDirection; readonly purpose: string | null; readonly endpoint: IntegrationEndpoint
  readonly databaseSourceId: number | null; readonly databaseObjectId: number | null; readonly contractFields: readonly IntegrationContractField[]
  readonly relatedFunctions: readonly IntegrationRelation[]; readonly relatedData: readonly IntegrationRelation[]; readonly evidence: readonly IntegrationEvidence[]; readonly unknownItems: readonly IntegrationUnknownItem[]
  readonly contextRail: { readonly participantSystems: readonly string[]; readonly relatedFunctionCount: number; readonly relatedDataCount: number; readonly openUnknownCount: number; readonly contractGaps: readonly string[] }
  readonly canDelete: boolean
  readonly availableActions: readonly string[]
}
export interface IntegrationRelation { readonly relationshipId: number; readonly id: number; readonly name: string; readonly relationType: string }
export interface IntegrationEvidence { readonly id: number; readonly evidenceType: string; readonly sourceTitle: string }
export interface IntegrationUnknownItem { readonly id: number; readonly question: string; readonly status: string }
export interface IntegrationWriteResponse { readonly id: number; readonly name: string; readonly integrationType: IntegrationType; readonly knowledgeStatus: KnowledgeStatus; readonly concurrencyToken: string }
export interface IntegrationContractFieldsResponse { readonly id: number; readonly fields: readonly IntegrationContractField[]; readonly concurrencyToken: string }

type ObjectValue = Readonly<Record<string, unknown>>
function object(value: unknown, field: string): ObjectValue { if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new TypeError(`${field} 必须是对象。`); return value as ObjectValue }
function string(value: unknown, field: string): string { if (typeof value !== 'string') throw new TypeError(`${field} 必须是字符串。`); return value }
function nullableString(value: unknown, field: string): string | null { return value === null || value === undefined ? null : string(value, field) }
function number(value: unknown, field: string, min=1): number { if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < min) throw new TypeError(`${field} 必须是安全整数。`); return value }
function nullableId(value: unknown, field: string): number | null { return value === null ? null : number(value, field) }
function array(value: unknown, field: string): readonly unknown[] { if (!Array.isArray(value)) throw new TypeError(`${field} 必须是数组。`); return value }
function boolean(value: unknown, field: string): boolean { if (typeof value !== 'boolean') throw new TypeError(`${field} 必须是布尔值。`); return value }
function status(value: unknown, field: string): KnowledgeStatus { const result=string(value,field); if(result==='Unknown'||result==='Inferred'||result==='Confirmed') return result; throw new TypeError(`${field} 无效。`) }
function integrationType(value: unknown, field: string): IntegrationType { const result=string(value,field); if(integrationTypes.includes(result as IntegrationType)) return result as IntegrationType; throw new TypeError(`${field} 无效。`) }
function direction(value: unknown, field: string): FlowDirection { const result=string(value,field); if(flowDirections.includes(result as FlowDirection)) return result as FlowDirection; throw new TypeError(`${field} 无效。`) }
function party(value: unknown, field: string): IntegrationParty { const item=object(value,field); return {systemId:nullableId(item.systemId,`${field}.systemId`),displayName:string(item.displayName,`${field}.displayName`)} }
function endpoint(value: unknown): IntegrationEndpoint { const item=object(value,'endpoint');return {url:nullableString(item.url,'endpoint.url'),method:nullableString(item.method,'endpoint.method'),exchange:nullableString(item.exchange,'endpoint.exchange'),topic:nullableString(item.topic,'endpoint.topic'),queue:nullableString(item.queue,'endpoint.queue'),filePath:nullableString(item.filePath,'endpoint.filePath')} }
function relation(value: unknown, field:string):IntegrationRelation {const item=object(value,field);return{relationshipId:number(item.relationshipId,`${field}.relationshipId`),id:number(item.id,`${field}.id`),name:string(item.name,`${field}.name`),relationType:string(item.relationType,`${field}.relationType`)}}
function field(value:unknown,index:number):IntegrationContractField{const item=object(value,`contractFields[${index}]`);if(typeof item.required!=='boolean')throw new TypeError(`contractFields[${index}].required 必须是布尔值。`);return{order:number(item.order,`contractFields[${index}].order`),fieldName:string(item.fieldName,`contractFields[${index}].fieldName`),dataType:nullableString(item.dataType,`contractFields[${index}].dataType`),required:item.required,description:nullableString(item.description,`contractFields[${index}].description`),sampleValue:nullableString(item.sampleValue,`contractFields[${index}].sampleValue`)}}
export function decodeIntegrationDetail(value: unknown): IntegrationDetailResponse { const root=object(value,'integration');const header=object(root.header,'header');const rail=object(root.contextRail,'contextRail');return {id:number(root.id,'id'),concurrencyToken:string(root.concurrencyToken,'concurrencyToken'),header:{name:string(header.name,'header.name'),integrationType:integrationType(header.integrationType,'header.integrationType'),knowledgeStatus:status(header.knowledgeStatus,'header.knowledgeStatus')},sourceParty:party(root.sourceParty,'sourceParty'),targetParty:party(root.targetParty,'targetParty'),flowDirection:direction(root.flowDirection,'flowDirection'),purpose:nullableString(root.purpose,'purpose'),endpoint:endpoint(root.endpoint),databaseSourceId:nullableId(root.databaseSourceId,'databaseSourceId'),databaseObjectId:nullableId(root.databaseObjectId,'databaseObjectId'),contractFields:array(root.contractFields,'contractFields').map(field),relatedFunctions:array(root.relatedFunctions,'relatedFunctions').map((item,index)=>relation(item,`relatedFunctions[${index}]`)),relatedData:array(root.relatedData,'relatedData').map((item,index)=>relation(item,`relatedData[${index}]`)),evidence:array(root.evidence,'evidence').map((value,index)=>{const item=object(value,`evidence[${index}]`);return{id:number(item.id,`evidence[${index}].id`),evidenceType:string(item.evidenceType,`evidence[${index}].evidenceType`),sourceTitle:string(item.sourceTitle,`evidence[${index}].sourceTitle`)}}),unknownItems:array(root.unknownItems,'unknownItems').map((value,index)=>{const item=object(value,`unknownItems[${index}]`);return{id:number(item.id,`unknownItems[${index}].id`),question:string(item.question,`unknownItems[${index}].question`),status:string(item.status,`unknownItems[${index}].status`)}}),contextRail:{participantSystems:array(rail.participantSystems,'contextRail.participantSystems').map((item,index)=>string(item,`contextRail.participantSystems[${index}]`)),relatedFunctionCount:number(rail.relatedFunctionCount,'contextRail.relatedFunctionCount',0),relatedDataCount:number(rail.relatedDataCount,'contextRail.relatedDataCount',0),openUnknownCount:number(rail.openUnknownCount,'contextRail.openUnknownCount',0),contractGaps:array(rail.contractGaps,'contextRail.contractGaps').map((item,index)=>string(item,`contextRail.contractGaps[${index}]`))},canDelete:boolean(root.canDelete,'canDelete'),availableActions:array(root.availableActions,'availableActions').map((item,index)=>string(item,`availableActions[${index}]`))} }
export function decodeIntegrationWrite(value: unknown): IntegrationWriteResponse { const root=object(value,'integration');return{id:number(root.id,'id'),name:string(root.name,'name'),integrationType:integrationType(root.integrationType,'integrationType'),knowledgeStatus:status(root.knowledgeStatus,'knowledgeStatus'),concurrencyToken:string(root.concurrencyToken,'concurrencyToken')} }
export function decodeIntegrationContractFields(value:unknown):IntegrationContractFieldsResponse{const root=object(value,'integrationContractFields');return{id:number(root.id,'id'),fields:array(root.fields,'fields').map(field),concurrencyToken:string(root.concurrencyToken,'concurrencyToken')}}
