<script setup lang="ts">
import { computed, onMounted, onUnmounted, watch } from 'vue'
import { DocumentAdd, EditPen, Plus, QuestionFilled } from '@element-plus/icons-vue'
import { useRoute, useRouter } from 'vue-router'
import { parseSafeApiId } from '../../../api/contracts/id'
import { useOverlayStore } from '../../../app/stores/overlays'
import { useActorStore } from '../../../app/stores/actor'
import KnowledgeStatusBadge from '../../../components/data-display/KnowledgeStatusBadge.vue'
import ErrorState from '../../../components/feedback/ErrorState.vue'
import LoadingState from '../../../components/feedback/LoadingState.vue'
import KnowledgeStatusProgressionPanel from '../../knowledge-status/components/KnowledgeStatusProgressionPanel.vue'
import { relationTypeLabels, relationTypes } from '../../relationships/api/relationshipContracts'
import { unknownItemStatusLabels, type UnknownItemStatus } from '../../unknown-items/api/unknownItemContracts'
import IntegrationContextRail from '../components/IntegrationContextRail.vue'
import { flowDirectionLabels, integrationTypeLabels, type IntegrationRelation } from '../api/integrationContracts'
import { useIntegrationDetail } from '../composables/useIntegrationDetail'
const route=useRoute();const router=useRouter();const overlays=useOverlayStore();const actorStore=useActorStore();const integrationId=computed(()=>parseSafeApiId(route.params.id));const{detail,loading,error,load}=useIntegrationDetail();const humanConfirmations=computed(()=>detail.value?.evidence.filter(item=>item.evidenceType==='HumanConfirmation').length??0)
function relationLabel(value:string){const match=relationTypes.find(item=>item===value);return match?relationTypeLabels[match]:value}async function reload(){if(integrationId.value!==null)await load(integrationId.value)}
function addRelationship(){if(!actorStore.canEdit||!detail.value)return;const systemId=detail.value.sourceParty.systemId??detail.value.targetParty.systemId;if(systemId===null)return;overlays.openDrawer({kind:'add-relationship',id:detail.value.id,mode:'create',payload:{source:{type:'Integration',id:detail.value.id},title:detail.value.header.name,systemId,systemName:detail.value.contextRail.participantSystems[0]??'当前系统'}})}
function addEvidence(){if(!actorStore.canEdit||!detail.value)return;overlays.openDrawer({kind:'add-evidence',id:detail.value.id,mode:'create',payload:{subject:{type:'Integration',id:detail.value.id},title:detail.value.header.name,knowledgeStatus:detail.value.header.knowledgeStatus,subjectDetailKey:null}})}
function createUnknown(){if(!actorStore.canEdit||!detail.value)return;const systemId=detail.value.sourceParty.systemId??detail.value.targetParty.systemId;if(systemId===null)return;overlays.openDialog({kind:'create-unknown-item',id:null,mode:'create',payload:{systemId,systemName:detail.value.contextRail.participantSystems[0]??'当前系统',target:{type:'Integration',id:detail.value.id},title:detail.value.header.name}})}
function openRelation(row:IntegrationRelation){overlays.openDrawer({kind:'relationship',id:row.relationshipId,mode:'read'})}function openEvidence(id:number){overlays.openDrawer({kind:'evidence',id,mode:'read'})}
watch(()=>route.params.id,()=>void reload());onMounted(()=>{void reload();window.addEventListener('integration:changed',reload);window.addEventListener('relationship:changed',reload);window.addEventListener('evidence:changed',reload);window.addEventListener('knowledge-status:changed',reload)});onUnmounted(()=>{window.removeEventListener('integration:changed',reload);window.removeEventListener('relationship:changed',reload);window.removeEventListener('evidence:changed',reload);window.removeEventListener('knowledge-status:changed',reload)})
</script>
<template><main class="integration-detail"><ErrorState v-if="integrationId===null" title="集成关系地址无效" message="请从系统、业务功能或关系详情重新进入。"/><LoadingState v-else-if="loading&&!detail" message="正在读取集成关系知识…"/><ErrorState v-else-if="error&&!detail" title="集成关系加载失败" :message="error" @retry="reload"/><template v-else-if="detail"><header class="integration-detail__header"><nav><button @click="router.push({name:'systems-list'})">系统</button><b>/</b><span>集成关系</span></nav><div class="integration-detail__title"><div><h1 class="technical-text">{{ detail.header.name }}</h1><p>{{ integrationTypeLabels[detail.header.integrationType] }} · {{ detail.sourceParty.displayName }} → {{ detail.targetParty.displayName }}</p></div><div><KnowledgeStatusBadge :status="detail.header.knowledgeStatus"/><el-button :icon="EditPen" @click="overlays.openDrawer({kind:'edit-integration',id:detail.id,mode:'edit'})">编辑</el-button></div></div><KnowledgeStatusProgressionPanel :id="detail.id" target-type="Integration" :title="detail.header.name" :status="detail.header.knowledgeStatus" :concurrency-token="detail.concurrencyToken" :evidence-count="detail.evidence.length" :human-confirmation-count="humanConfirmations" :can-change="detail.availableActions.includes('ChangeKnowledgeStatus')"/></header><p v-if="error" class="integration-inline-error">{{ error }}</p>
<section class="integration-section"><header><h2>概览</h2></header><dl class="integration-overview"><div><dt>集成类型</dt><dd>{{ integrationTypeLabels[detail.header.integrationType] }}</dd></div><div><dt>数据流向</dt><dd>{{ flowDirectionLabels[detail.flowDirection] }}</dd></div><div><dt>来源方</dt><dd><strong>{{ detail.sourceParty.displayName }}</strong><small v-if="detail.sourceParty.systemId" class="technical-text">System #{{ detail.sourceParty.systemId }}</small></dd></div><div><dt>目标方</dt><dd><strong>{{ detail.targetParty.displayName }}</strong><small v-if="detail.targetParty.systemId" class="technical-text">System #{{ detail.targetParty.systemId }}</small></dd></div><div class="wide"><dt>用途</dt><dd>{{ detail.purpose ?? '尚未补充用途。' }}</dd></div></dl></section>
<section class="integration-section"><header><h2>消息 / 数据流</h2></header><div class="integration-flow"><span>{{ detail.sourceParty.displayName }}</span><b>→</b><span class="technical-text">{{ detail.endpoint.topic ?? detail.endpoint.queue ?? detail.endpoint.url ?? detail.endpoint.filePath ?? '数据库依赖' }}</span><b>→</b><span>{{ detail.targetParty.displayName }}</span></div><dl class="integration-endpoint"><div v-if="detail.endpoint.url"><dt>URL</dt><dd class="technical-text">{{ detail.endpoint.method }} {{ detail.endpoint.url }}</dd></div><div v-if="detail.endpoint.exchange"><dt>Exchange</dt><dd class="technical-text">{{ detail.endpoint.exchange }}</dd></div><div v-if="detail.endpoint.topic"><dt>Topic</dt><dd class="technical-text">{{ detail.endpoint.topic }}</dd></div><div v-if="detail.endpoint.queue"><dt>Queue</dt><dd class="technical-text">{{ detail.endpoint.queue }}</dd></div><div v-if="detail.endpoint.filePath"><dt>文件路径</dt><dd class="technical-text">{{ detail.endpoint.filePath }}</dd></div></dl></section>
<section class="integration-section"><header><h2>消息 / 数据契约</h2><span>{{ detail.contractFields.length }} 项</span></header><el-table v-if="detail.contractFields.length" :data="detail.contractFields" class="integration-table"><el-table-column prop="order" label="#" width="52"/><el-table-column prop="fieldName" label="字段" min-width="190"><template #default="scope"><strong class="technical-text">{{ scope.row.fieldName }}</strong></template></el-table-column><el-table-column prop="dataType" label="类型" min-width="130"><template #default="scope"><span class="technical-text">{{ scope.row.dataType ?? '—' }}</span></template></el-table-column><el-table-column label="必填" width="70"><template #default="scope">{{ scope.row.required?'是':'否' }}</template></el-table-column><el-table-column prop="description" label="说明" min-width="220"/><el-table-column prop="sampleValue" label="示例值" min-width="160"/></el-table><div v-else class="integration-empty">尚未补充消息 / 数据契约字段；可在编辑抽屉中渐进补充。</div></section>
<section class="integration-section"><header><h2>关联业务功能</h2><el-button text type="primary" :icon="Plus" @click="addRelationship">添加关系</el-button></header><el-table v-if="detail.relatedFunctions.length" :data="detail.relatedFunctions" class="integration-table" @row-click="openRelation"><el-table-column prop="name" label="业务功能" min-width="260"><template #default="scope"><strong class="technical-text link-text">{{ scope.row.name }}</strong></template></el-table-column><el-table-column label="关系类型" width="150"><template #default="scope">{{ relationLabel(scope.row.relationType) }}</template></el-table-column></el-table><div v-else class="integration-empty">尚未记录发布、消费或使用该集成的业务功能。</div></section>
<section class="integration-section"><header><h2>关联数据</h2></header><el-table v-if="detail.relatedData.length" :data="detail.relatedData" class="integration-table" @row-click="openRelation"><el-table-column prop="name" label="数据对象" min-width="280"><template #default="scope"><strong class="technical-text link-text">{{ scope.row.name }}</strong></template></el-table-column><el-table-column label="关系类型" width="150"><template #default="scope">{{ relationLabel(scope.row.relationType) }}</template></el-table-column></el-table><div v-else class="integration-empty">尚未记录数据库依赖或关联数据。</div></section>
<div class="integration-two"><section class="integration-section"><header><h2>证据</h2><el-button text type="primary" :icon="DocumentAdd" @click="addEvidence">添加证据</el-button></header><button v-for="item in detail.evidence" :key="item.id" class="integration-list-button" @click="openEvidence(item.id)"><span>{{ item.evidenceType }}</span><strong class="technical-text">{{ item.sourceTitle }}</strong></button><div v-if="!detail.evidence.length" class="integration-empty">尚无证据；当前集成可保持“未知”。</div></section><section class="integration-section"><header><h2>待确认事项</h2><el-button text type="primary" :icon="QuestionFilled" @click="createUnknown">创建待确认事项</el-button></header><button v-for="item in detail.unknownItems" :key="item.id" class="integration-list-button" @click="router.push({name:'unknown-item-detail',params:{id:String(item.id)}})"><strong>{{ item.question }}</strong><span>{{ unknownItemStatusLabels[item.status as UnknownItemStatus]??item.status }}</span></button><div v-if="!detail.unknownItems.length" class="integration-empty">当前集成没有开放待确认事项。</div></section></div><Teleport defer to="#context-rail-content"><IntegrationContextRail :detail="detail"/></Teleport></template></main></template>
<style src="../integrations.css"></style>
