import { apiClient } from '../../../api/client/apiClient'
import { isSafeApiId } from '../../../api/contracts/id'
import { decodeAddRelationship, decodeDescription, decodeRelatedKnowledge, decodeRelationshipDetail, decodeStatusChange, decodeTargets, type AddRelationshipRequest, type AddRelationshipResponse, type ChangeRelationshipStatusRequest, type KnowledgeTargetType, type KnowledgeTargetsResponse, type RelatedKnowledge, type RelationType, type RelationshipDetailResponse, type UpdateRelationshipDescriptionRequest } from './relationshipContracts'

export function searchRelationshipTargets(p:{systemId?:number;sourceType:string;sourceId:number;relationType:RelationType;q:string},signal?:AbortSignal):Promise<KnowledgeTargetsResponse>{const query=new URLSearchParams({purpose:'RelationTarget',sourceType:p.sourceType,sourceId:String(p.sourceId),relationType:p.relationType,q:p.q,page:'1',pageSize:'20'});if(p.systemId!==undefined)query.set('systemId',String(p.systemId));return apiClient.get(`/knowledge-targets?${query}`,{signal,decode:decodeTargets})}
export function addRelationship(request:AddRelationshipRequest):Promise<AddRelationshipResponse>{return apiClient.post('/relationships',request,{decode:decodeAddRelationship})}
export function getRelationshipDetail(id:number,signal?:AbortSignal):Promise<RelationshipDetailResponse>{if(!isSafeApiId(id))return Promise.reject(new RangeError('关系 ID 无效。'));return apiClient.get(`/relationships/${id}`,{signal,decode:decodeRelationshipDetail})}
export function updateRelationshipDescription(id:number,request:UpdateRelationshipDescriptionRequest){return apiClient.put(`/relationships/${id}/description`,request,{decode:decodeDescription})}
export function changeRelationshipStatus(id:number,request:ChangeRelationshipStatusRequest){return apiClient.put(`/relationships/${id}/knowledge-status`,request,{decode:decodeStatusChange})}
export function getRelatedKnowledge(objectType:KnowledgeTargetType,objectId:number,signal?:AbortSignal):Promise<readonly RelatedKnowledge[]>{if(!isSafeApiId(objectId))return Promise.reject(new RangeError('对象 ID 无效。'));return apiClient.get(`/relationships?objectType=${encodeURIComponent(objectType)}&objectId=${objectId}`,{signal,decode:decodeRelatedKnowledge})}
export function deleteRelationship(id:number):Promise<void>{if(!isSafeApiId(id))return Promise.reject(new RangeError('关系 ID 无效。'));return apiClient.delete(`/relationships/${id}`,{decode:()=>undefined})}
