<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useOverlayStore } from '../../../app/stores/overlays'
import KnowledgeProgression from '../../../components/data-display/KnowledgeProgression.vue'
import { evidenceTypeLabels, type EvidenceType } from '../../evidence/api/evidenceContracts'
import { integrationsApi } from '../api/integrationsApi'
import { flowDirectionLabels, integrationTypeLabels, type IntegrationDetailResponse } from '../api/integrationContracts'
const props=defineProps<{integrationId:number|null}>();const overlays=useOverlayStore();const router=useRouter();const detail=ref<IntegrationDetailResponse|null>(null);const error=ref<string|null>(null)
const evidenceTypeLabel=(value:string)=>evidenceTypeLabels[value as EvidenceType]??value
onMounted(async()=>{if(!props.integrationId){error.value='集成关系 ID 无效。';return}try{detail.value=await integrationsApi.detail(props.integrationId)}catch(caught:unknown){error.value=caught instanceof Error?caught.message:'集成关系预览失败。'}})
async function openDetail(){if(!detail.value)return;overlays.closeDrawer();await router.push({name:'integration-detail',params:{id:String(detail.value.id)}})}
</script>
<template><section class="integration-drawer"><header class="skh-drawer-header"><div><small>集成关系详情</small><h2>{{ detail?.header.name ?? '读取中…' }}</h2><p>{{ detail ? `${integrationTypeLabels[detail.header.integrationType]} · ${detail.sourceParty.displayName} → ${detail.targetParty.displayName}` : '' }}</p></div><button type="button" aria-label="关闭集成关系详情" @click="overlays.requestDrawerClose">×</button></header><p v-if="error" class="integration-drawer__state">{{ error }}</p><template v-else-if="detail"><section><h3>知识进展（只读）</h3><KnowledgeProgression :status="detail.header.knowledgeStatus"/></section><section><h3>概览</h3><dl><div><dt>类型</dt><dd>{{ integrationTypeLabels[detail.header.integrationType] }}</dd></div><div><dt>方向</dt><dd>{{ flowDirectionLabels[detail.flowDirection] }}</dd></div><div><dt>用途</dt><dd>{{ detail.purpose ?? '尚未补充' }}</dd></div></dl></section><section><h3>消息 / 数据流</h3><div class="integration-preview-flow"><span>{{ detail.sourceParty.displayName }}</span><b>→</b><span class="technical-text">{{ detail.endpoint.topic ?? detail.endpoint.queue ?? detail.endpoint.url ?? detail.endpoint.filePath ?? '数据库依赖' }}</span><b>→</b><span>{{ detail.targetParty.displayName }}</span></div></section><section><h3>当前关系</h3><dl><div><dt>关联功能</dt><dd>{{ detail.relatedFunctions.length }} 项</dd></div><div><dt>关联数据</dt><dd>{{ detail.relatedData.length }} 项</dd></div><div><dt>契约字段</dt><dd>{{ detail.contractFields.length }} 项</dd></div></dl></section><section><h3>证据 <b>{{ detail.evidence.length }}</b></h3><button v-for="item in detail.evidence" :key="item.id" class="integration-drawer__row"><span>{{ evidenceTypeLabel(item.evidenceType) }}</span><strong class="technical-text">{{ item.sourceTitle }}</strong></button><p v-if="!detail.evidence.length">尚无证据。</p></section><section><h3>待确认事项 <b>{{ detail.unknownItems.length }}</b></h3><p v-for="item in detail.unknownItems" :key="item.id">{{ item.question }}</p><p v-if="!detail.unknownItems.length">当前没有开放缺口。</p></section></template><footer><el-button type="primary" :disabled="!detail" @click="openDetail">打开集成关系详情</el-button></footer></section></template>
