<script setup lang="ts">
import { computed, onMounted, onUnmounted, watch } from 'vue'
import { Delete, DocumentChecked, EditPen, Link, Plus, QuestionFilled } from '@element-plus/icons-vue'
import { useRoute, useRouter } from 'vue-router'
import { parseSafeApiId } from '../../../api/contracts/id'
import { useOverlayStore } from '../../../app/stores/overlays'
import { useActorStore } from '../../../app/stores/actor'
import KnowledgeStatusBadge from '../../../components/data-display/KnowledgeStatusBadge.vue'
import ErrorState from '../../../components/feedback/ErrorState.vue'
import LoadingState from '../../../components/feedback/LoadingState.vue'
import KnowledgeStatusProgressionPanel from '../../knowledge-status/components/KnowledgeStatusProgressionPanel.vue'
import { relationTypeLabels, relationTypes } from '../../relationships/api/relationshipContracts'
import { unknownItemStatusLabels, type UnknownItemStatus } from '../../unknown-items/api/unknownItemContracts'
import BusinessRuleContextRail from '../components/BusinessRuleContextRail.vue'
import type { BusinessRuleRelationship } from '../api/businessRuleContracts'
import { businessRulesApi } from '../api/businessRulesApi'
import { useBusinessRuleDetail } from '../composables/useBusinessRuleDetail'
import { openDeleteDialog } from '../../soft-delete/deleteDialog'

const route=useRoute();const router=useRouter();const overlays=useOverlayStore();const actorStore=useActorStore();const ruleId=computed(()=>parseSafeApiId(route.params.id));const{detail,loading,error,load}=useBusinessRuleDetail();const humanConfirmations=computed(()=>detail.value?.evidence.filter(item=>item.evidenceType==='HumanConfirmation').length??0)
function relationLabel(value:string){const match=relationTypes.find(item=>item===value);return match?relationTypeLabels[match]:value}
async function reload(){if(ruleId.value!==null)await load(ruleId.value)}
function addRelationship(){if(!actorStore.canEdit||!detail.value)return;overlays.openDrawer({kind:'add-relationship',id:detail.value.id,mode:'create',payload:{source:{type:'BusinessRule',id:detail.value.id},title:detail.value.header.name,systemId:detail.value.system.id,systemName:detail.value.system.name}})}
function addEvidence(){if(!actorStore.canEdit||!detail.value)return;overlays.openDrawer({kind:'add-evidence',id:detail.value.id,mode:'create',payload:{subject:{type:'BusinessRule',id:detail.value.id},title:`${detail.value.system.name} · ${detail.value.header.name}`,knowledgeStatus:detail.value.header.knowledgeStatus,subjectDetailKey:null}})}
function createUnknown(){if(!actorStore.canEdit||!detail.value)return;overlays.openDialog({kind:'create-unknown-item',id:null,mode:'create',payload:{systemId:detail.value.system.id,systemName:detail.value.system.name,target:{type:'BusinessRule',id:detail.value.id},title:detail.value.header.name}})}
function openRelationship(id:number){overlays.openDrawer({kind:'relationship',id,mode:'read'})}
function openFieldRow(row:BusinessRuleRelationship){overlays.openDrawer({kind:'database-column',id:row.id,mode:'read'})}
function openFunctionRow(row:BusinessRuleRelationship){void router.push({name:'business-function-detail',params:{id:String(row.id)}})}
function openEvidence(id:number){overlays.openDrawer({kind:'evidence',id,mode:'read'})}
function requestDelete(){if(!detail.value?.canDelete)return;const current=detail.value;openDeleteDialog(overlays,{objectTypeLabel:'业务规则',actionLabel:'删除业务规则',displayName:current.header.name,concurrencyToken:current.concurrencyToken,execute:()=>businessRulesApi.delete(current.id,current.concurrencyToken),onDeleted:()=>router.push({name:'business-functions-list'}),onRefresh:reload,onUnavailable:()=>router.push({name:'business-functions-list'})})}
watch(()=>route.params.id,()=>void reload());onMounted(()=>{void reload();window.addEventListener('business-rule:changed',reload);window.addEventListener('relationship:changed',reload);window.addEventListener('evidence:changed',reload);window.addEventListener('knowledge-status:changed',reload)});onUnmounted(()=>{window.removeEventListener('business-rule:changed',reload);window.removeEventListener('relationship:changed',reload);window.removeEventListener('evidence:changed',reload);window.removeEventListener('knowledge-status:changed',reload)})
</script>
<template><main class="business-rule-detail"><ErrorState v-if="ruleId===null" title="业务规则地址无效" message="请从关联业务功能重新进入。"/><LoadingState v-else-if="loading&&!detail" message="正在读取业务规则知识…"/><ErrorState v-else-if="error&&!detail" title="业务规则加载失败" :message="error" @retry="reload"/><template v-else-if="detail"><header class="rule-detail-header"><nav><button @click="router.push({name:'business-functions-list'})">业务功能</button><b>/</b><span class="technical-text">{{ detail.system.name }}</span><b>/</b><span>业务规则</span></nav><div class="rule-detail-header__title"><div><h1>{{ detail.header.name }}</h1><p>{{ detail.description }}</p></div><div><KnowledgeStatusBadge :status="detail.header.knowledgeStatus"/><el-button v-if="detail.canDelete" type="danger" plain :icon="Delete" @click="requestDelete">删除业务规则</el-button><el-button :icon="EditPen" @click="overlays.openDrawer({kind:'edit-business-rule',id:detail.id,mode:'edit'})">编辑</el-button></div></div><KnowledgeStatusProgressionPanel :id="detail.id" target-type="BusinessRule" :title="detail.header.name" :status="detail.header.knowledgeStatus" :concurrency-token="detail.concurrencyToken" :evidence-count="detail.evidence.length" :human-confirmation-count="humanConfirmations" :can-change="detail.availableActions.includes('ChangeKnowledgeStatus')"/></header><p v-if="error" class="rule-inline-error">{{ error }}</p>
<section class="rule-section rule-overview"><header><h2>概览</h2></header><dl><div><dt>所属系统</dt><dd class="technical-text">{{ detail.system.name }}</dd></div><div><dt>规则名称</dt><dd>{{ detail.header.name }}</dd></div><div class="wide"><dt>用途</dt><dd>{{ detail.description }}</dd></div></dl></section>
<section class="rule-section rule-definition"><header><h2>规则定义</h2></header><dl><div><dt>条件</dt><dd class="technical-text code-value">{{ detail.condition??'尚未补充条件。' }}</dd></div><div><dt>结果</dt><dd>{{ detail.result??'尚未补充结果。' }}</dd></div></dl></section>
<section class="rule-section"><header><h2>输入数据</h2><span>{{ detail.inputData.length }} 项</span></header><el-table v-if="detail.inputData.length" :data="detail.inputData" class="rule-table"><el-table-column prop="name" label="名称" min-width="220"><template #default="scope"><span class="technical-text">{{ scope.row.name }}</span></template></el-table-column><el-table-column prop="description" label="说明" min-width="300"/></el-table><div v-else class="rule-empty">尚未补充结构化输入数据。</div></section>
<section class="rule-section"><header><h2>关联业务功能</h2><span>{{ detail.relatedFunctions.length }} 项</span></header><el-table v-if="detail.relatedFunctions.length" :data="detail.relatedFunctions" class="rule-table" @row-click="openFunctionRow"><el-table-column prop="name" label="业务功能" min-width="280"><template #default="scope"><span class="technical-text link-text">{{ scope.row.name }}</span></template></el-table-column><el-table-column label="关系类型" width="140"><template #default="scope">{{ relationLabel(scope.row.relationType) }}</template></el-table-column></el-table><div v-else class="rule-empty">尚无业务功能通过 <span class="technical-text">AppliesRule</span> 关联此规则；请从业务功能详情添加该关系。</div></section>
<section class="rule-section"><header><h2>关联字段</h2><el-button text type="primary" :icon="Plus" @click="addRelationship">添加关系</el-button></header><el-table v-if="detail.relatedFields.length" :data="detail.relatedFields" class="rule-table" @row-click="openFieldRow"><el-table-column prop="name" label="字段" min-width="320"><template #default="scope"><span class="technical-text link-text">{{ scope.row.name }}</span></template></el-table-column><el-table-column label="用途" width="160"><template #default="scope">{{ relationLabel(scope.row.relationType) }}</template></el-table-column></el-table><div v-else class="rule-empty">尚未记录规则使用的字段。</div></section>
<div class="rule-two-column"><section class="rule-section"><header><h2>集成关系</h2><span>{{ detail.integrations.length }} 项</span></header><div v-if="detail.integrations.length"><button v-for="item in detail.integrations" :key="item.relationshipId" class="rule-list-button" @click="openRelationship(item.relationshipId)"><el-icon><Link/></el-icon><span><strong class="technical-text">{{ item.name }}</strong><small>{{ relationLabel(item.relationType) }}</small></span></button></div><div v-else class="rule-empty">尚未记录集成依赖。</div></section><section class="rule-section rule-evidence"><header><h2>证据</h2><el-button class="skh-section-action skh-evidence-action" type="primary" :icon="DocumentChecked" @click="addEvidence">添加证据</el-button></header><button v-for="item in detail.evidence" :key="item.id" @click="openEvidence(item.id)"><span>{{ item.evidenceType }}</span><strong class="technical-text">{{ item.sourceTitle }}</strong></button><div v-if="!detail.evidence.length" class="rule-empty">尚无证据；当前规则仍可保持“未知”。</div></section></div>
<section class="rule-section rule-unknown"><header><h2>待确认事项</h2><el-button text type="primary" :icon="QuestionFilled" @click="createUnknown">创建待确认事项</el-button></header><button v-for="item in detail.unknownItems" :key="item.id" @click="router.push({name:'unknown-item-detail',params:{id:String(item.id)}})"><strong>{{ item.question }}</strong><span>{{ unknownItemStatusLabels[item.status as UnknownItemStatus]??item.status }}</span></button><div v-if="!detail.unknownItems.length" class="rule-empty">当前规则没有开放待确认事项。</div></section>
<Teleport defer to="#context-rail-content"><BusinessRuleContextRail :detail="detail"/></Teleport></template></main></template>
<style src="../business-rules.css"></style>
