<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useOverlayStore } from '../../../app/stores/overlays'
import KnowledgeProgression from '../../../components/data-display/KnowledgeProgression.vue'
import KnowledgeStatusBadge from '../../../components/data-display/KnowledgeStatusBadge.vue'
import { evidenceTypeLabels, type EvidenceType } from '../../evidence/api/evidenceContracts'
import { businessRulesApi } from '../api/businessRulesApi'
import type { BusinessRuleDetailResponse } from '../api/businessRuleContracts'
const props=defineProps<{ruleId:number|null}>();const detail=ref<BusinessRuleDetailResponse|null>(null);const error=ref<string|null>(null);const overlays=useOverlayStore();const router=useRouter()
const evidenceTypeLabel=(value:string)=>evidenceTypeLabels[value as EvidenceType]??value
onMounted(async()=>{if(!props.ruleId){error.value='业务规则 ID 无效。';return}try{detail.value=await businessRulesApi.detail(props.ruleId)}catch(caught:unknown){error.value=caught instanceof Error?caught.message:'业务规则预览失败。'}})
async function openDetail(){if(!detail.value)return;overlays.closeDrawer();await router.push({name:'business-rule-detail',params:{id:String(detail.value.id)}})}
</script>
<template><section class="rule-drawer rule-preview-drawer"><header class="skh-drawer-header"><div><small>业务规则详情</small><h2>{{ detail?.header.name ?? '读取中…' }}</h2><p>{{ detail ? `${detail.system.name} · 业务规则` : '' }}</p></div><button type="button" aria-label="关闭业务规则详情" @click="overlays.requestDrawerClose">×</button></header><div v-if="error" class="rule-drawer__state">{{ error }}</div><template v-else-if="detail"><section><h3>知识进展（只读）</h3><KnowledgeProgression :status="detail.header.knowledgeStatus" /></section><section><h3>规则定义</h3><dl><div><dt>描述</dt><dd>{{ detail.description }}</dd></div><div><dt>条件</dt><dd class="technical-text">{{ detail.condition ?? '尚未补充' }}</dd></div><div><dt>结果</dt><dd>{{ detail.result ?? '尚未补充' }}</dd></div></dl></section><section><h3>当前关系</h3><dl><div><dt>业务功能</dt><dd>{{ detail.relatedFunctions.length }} 项</dd></div><div><dt>关联字段</dt><dd>{{ detail.relatedFields.length }} 项</dd></div><div><dt>集成关系</dt><dd>{{ detail.integrations.length }} 项</dd></div></dl></section><section><h3>关联字段</h3><table v-if="detail.relatedFields.length"><tbody><tr v-for="item in detail.relatedFields" :key="item.relationshipId"><td class="technical-text">{{ item.name }}</td><td><KnowledgeStatusBadge :status="detail.header.knowledgeStatus" /></td></tr></tbody></table><p v-else>尚未记录字段关系。</p></section><section><h3>证据 <b>{{ detail.evidence.length }}</b></h3><button v-for="item in detail.evidence" :key="item.id" class="rule-preview-evidence"><span>{{ evidenceTypeLabel(item.evidenceType) }}</span><strong class="technical-text">{{ item.sourceTitle }}</strong></button><p v-if="!detail.evidence.length">尚无证据。</p></section><section class="rule-preview-gaps"><h3>待确认事项 <b>{{ detail.unknownItems.length }}</b></h3><p v-for="item in detail.unknownItems" :key="item.id">{{ item.question }}</p><p v-if="!detail.unknownItems.length">当前没有开放缺口。</p></section></template><footer><el-button type="primary" :disabled="!detail" @click="openDetail">打开业务规则详情</el-button></footer></section></template>
