<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import type { FormInstance, FormRules } from 'element-plus'
import { ArrowLeft, Connection, DocumentChecked } from '@element-plus/icons-vue'
import { ApiError } from '../../../api/errors/ApiError'
import { useActorStore } from '../../../app/stores/actor'
import { useOverlayStore } from '../../../app/stores/overlays'
import type { SystemSummary } from '../../systems/api/systemsContracts'
import { businessRulesApi } from '../api/businessRulesApi'
import type { BusinessRuleWriteResponse } from '../api/businessRuleContracts'

const props=defineProps<{systems:readonly SystemSummary[];initialSystemId?:number}>();const emit=defineEmits<{created:[rule:BusinessRuleWriteResponse]}>();const actors=useActorStore();const overlays=useOverlayStore();const formRef=ref<FormInstance>();const submitting=ref(false);const error=ref<string|null>(null)
const form=reactive({systemId:props.initialSystemId,name:'',description:'',condition:'',result:'',inputData:[{name:'',description:''}]})
const rules:FormRules<typeof form>={systemId:[{required:true,message:'请选择所属系统',trigger:'change'}],name:[{required:true,message:'请输入规则名称',trigger:'blur'}],description:[{required:true,message:'请输入规则描述',trigger:'blur'}]}
watch(()=>[props.initialSystemId,props.systems] as const,()=>{if(!form.systemId)form.systemId=props.initialSystemId??props.systems[0]?.id},{immediate:true})
const actorDescription=computed(()=>actors.role?`${actors.displayName} · ${actors.role}`:actors.displayName)
function back(){overlays.openDialog({kind:'create-knowledge-object',id:null,mode:'create'})}
function addInput(){form.inputData.push({name:'',description:''})}
function removeInput(index:number){form.inputData.splice(index,1)}
async function submit(){error.value=null;const valid=await formRef.value?.validate().catch(()=>false);if(!valid||!form.systemId||submitting.value)return;submitting.value=true;try{const inputData=form.inputData.filter(item=>item.name.trim()).map(item=>({name:item.name.trim(),description:item.description.trim()||null}));emit('created',await businessRulesApi.create({systemId:form.systemId,name:form.name.trim(),description:form.description.trim(),condition:form.condition.trim()||null,result:form.result.trim()||null,inputData,actor:actors.actor}))}catch(caught:unknown){error.value=caught instanceof ApiError?caught.message:caught instanceof Error?caught.message:'业务规则创建失败。'}finally{submitting.value=false}}
</script>
<template><section class="create-rule-dialog"><header class="authoring-header authoring-header--form"><div><button class="authoring-back" @click="back"><el-icon><ArrowLeft /></el-icon> 选择知识类型</button><h2>新增业务规则</h2><p>先记录最小必要信息；条件、关系和证据可在创建后渐进补充。</p></div><button class="authoring-close" @click="overlays.closeDialog">×</button></header><div class="authoring-progression"><span class="authoring-progression__step authoring-progression__step--active"><b>1</b>基本信息（当前）</span><span class="authoring-progression__line"></span><span class="authoring-progression__step"><b>2</b>关系（创建后）</span><span class="authoring-progression__line"></span><span class="authoring-progression__step"><b>3</b>证据（创建后）</span></div><div class="create-rule-dialog__body"><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><el-alert v-if="error" class="authoring-form-alert" type="error" :title="error" :closable="false" show-icon/><el-form-item label="所属系统" prop="systemId" required><el-select v-model="form.systemId" filterable><el-option v-for="system in systems" :key="system.id" :label="`${system.name} · ${system.displayName}`" :value="system.id" /></el-select></el-form-item><el-form-item label="规则名称" prop="name" required><el-input v-model="form.name" placeholder="例如 显示状态计算" /></el-form-item><el-form-item label="简短描述" prop="description" required><el-input v-model="form.description" type="textarea" :rows="3" placeholder="说明这条规则解决什么业务判断" /></el-form-item><el-collapse><el-collapse-item title="稍后补充：条件、结果与输入数据" name="advanced"><el-form-item label="条件"><el-input v-model="form.condition" class="technical-input" placeholder="STATE_FLAG IN ('10','20','30')" /></el-form-item><el-form-item label="结果"><el-input v-model="form.result" type="textarea" :rows="2" /></el-form-item><label class="rule-input-editor__label">输入数据</label><div v-for="(item,index) in form.inputData" :key="index" class="rule-input-editor"><el-input v-model="item.name" placeholder="名称，例如 STATE_FLAG" /><el-input v-model="item.description" placeholder="说明（可选）" /><el-button text @click="removeInput(index)">移除</el-button></div><el-button text type="primary" @click="addInput">+ 添加输入</el-button></el-collapse-item></el-collapse></el-form><aside><h3>创建后的下一步</h3><div><el-icon><Connection /></el-icon><span><strong>添加关系</strong><small>连接业务功能、字段与集成</small></span></div><div><el-icon><DocumentChecked /></el-icon><span><strong>添加证据</strong><small>说明为什么相信这条规则</small></span></div><section><span>知识状态</span><p>创建后保持“未知”，不会自动推进。</p><strong class="knowledge-status-badge knowledge-status-badge--unknown">未知</strong></section><footer>创建人：{{ actorDescription }}</footer></aside></div><footer class="authoring-actions"><p>关系、证据和状态均通过后续明确操作维护。</p><div><el-button @click="overlays.closeDialog">取消</el-button><el-button type="primary" :loading="submitting" @click="submit">创建业务规则</el-button></div></footer></section></template>
