<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import type { FormInstance, FormRules } from 'element-plus'
import { ElMessage } from 'element-plus'
import { useActorStore } from '../../../app/stores/actor'
import { useOverlayStore } from '../../../app/stores/overlays'
import KnowledgeProgression from '../../../components/data-display/KnowledgeProgression.vue'
import { businessRulesApi } from '../api/businessRulesApi'
import type { BusinessRuleDetailResponse } from '../api/businessRuleContracts'

const props=defineProps<{ruleId:number|null}>();const actors=useActorStore();const overlays=useOverlayStore();const loading=ref(true);const saving=ref(false);const error=ref<string|null>(null);const detail=ref<BusinessRuleDetailResponse|null>(null);const form=reactive({name:'',description:'',condition:'',result:'',inputData:[] as {name:string;description:string}[]})
const formRef=ref<FormInstance>();const rules:FormRules<typeof form>={name:[{required:true,message:'请输入规则名称',trigger:'blur'}],description:[{required:true,message:'请输入简短描述',trigger:'blur'}]}
async function load(){if(!props.ruleId){error.value='业务规则 ID 无效。';return}loading.value=true;try{detail.value=await businessRulesApi.detail(props.ruleId);form.name=detail.value.header.name;form.description=detail.value.description;form.condition=detail.value.condition??'';form.result=detail.value.result??'';form.inputData=detail.value.inputData.map(item=>({name:item.name,description:item.description??''}))}catch(caught:unknown){error.value=caught instanceof Error?caught.message:'业务规则加载失败。'}finally{loading.value=false}}
function addInput(){form.inputData.push({name:'',description:''})}
async function save(){if(!detail.value)return;error.value=null;const valid=await formRef.value?.validate().catch(()=>false);if(!valid)return;saving.value=true;try{await businessRulesApi.update(detail.value.id,{name:form.name.trim(),description:form.description.trim(),condition:form.condition.trim()||null,result:form.result.trim()||null,inputData:form.inputData.filter(item=>item.name.trim()).map(item=>({name:item.name.trim(),description:item.description.trim()||null})),actor:actors.actor,concurrencyToken:detail.value.concurrencyToken});overlays.closeDrawer();window.dispatchEvent(new CustomEvent('business-rule:changed'));ElMessage.success('业务规则已保存。')}catch(caught:unknown){error.value=caught instanceof Error?caught.message:'保存失败。'}finally{saving.value=false}}
onMounted(()=>void load())
</script>
<template><section class="rule-drawer rule-edit-drawer"><header class="skh-drawer-header"><div><small>编辑业务规则</small><h2>{{ detail?.header.name ?? '读取中…' }}</h2><p class="technical-text">{{ detail?.system.name }}</p></div><button type="button" aria-label="关闭业务规则编辑" @click="overlays.requestDrawerClose">×</button></header><div v-if="loading" class="rule-drawer__state">正在读取规则…</div><div v-else-if="detail" class="rule-edit-drawer__body"><section class="rule-edit-status"><strong>知识状态</strong><KnowledgeProgression :status="detail.header.knowledgeStatus" /><p>知识状态不能通过此表单直接切换。</p></section><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><el-alert v-if="error" class="authoring-form-alert" type="error" :title="error" :closable="false" show-icon/><el-form-item label="规则名称" prop="name" required><el-input v-model="form.name" /></el-form-item><el-form-item label="简短描述" prop="description" required><el-input v-model="form.description" type="textarea" :rows="3" /></el-form-item><el-divider content-position="left">规则定义</el-divider><el-form-item label="条件"><el-input v-model="form.condition" class="technical-input" type="textarea" :rows="3" /></el-form-item><el-form-item label="结果"><el-input v-model="form.result" type="textarea" :rows="3" /></el-form-item><el-divider content-position="left">输入数据</el-divider><div v-for="(item,index) in form.inputData" :key="index" class="rule-input-editor"><el-input v-model="item.name" class="technical-input" placeholder="输入名称" /><el-input v-model="item.description" placeholder="说明" /><el-button text @click="form.inputData.splice(index,1)">移除</el-button></div><el-button text type="primary" @click="addInput">+ 添加输入</el-button></el-form><aside><strong>关系与证据单独维护</strong><p>保存不会修改所属系统、知识状态、关系、证据或待确认事项。</p></aside></div><footer><el-button @click="overlays.requestDrawerClose">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存业务规则</el-button></footer></section></template>
